### ISSUE TITLE
'@adyen-web' exists twice in node_modules

### ISSUE THREAD

**Issue by TayyabSalmanMRM1996** [Adyen/adyen-salesforce-headless-commerce-pwa#146]
When installing node_modules, `@adyen-web` is included twice. Doesn't `node_modules/@adyen/adyen-salesforce-pwa/dist/app` already include `@adyen-web`?

Adding `@adyen/adyen-salesforce-pwa` should be enough and it appears that we should not add `@adyen-web` of big size which will eventually impact performance:

<img width="430" alt="image" src="https://github.com/Adyen/adyen-salesforce-headless-commerce-pwa/assets/162591335/261c23f4-be99-4391-b568-00f602e852ab">

Looks like that's the way the package is built:
[https://github.com/Adyen/adyen-salesforce-headless-commerce-pwa/blob/main/packages/adyen-salesforce-pwa/webpack.config.js#L70C1-L72C29](https://github.com/Adyen/adyen-salesforce-headless-commerce-pwa/blob/main/packages/adyen-salesforce-pwa/webpack.config.js#L70C1-L72C29).

Not sure why we need both `@adyen/adyen-salesforce-pwa` and `@adyen-web`. The size of `@adyen-web` is already big and it appears to be included twice.

Can you look into this duplication?

**Comment by amihajlovski** [comment]
Hi @TayyabSalmanMRM1996 

We are investigating this issue internally and will provide a solution of the problem in our future releases. 

Kind Regards
Aleksandar
Adyen

**Comment by amihajlovski** [comment]
Hello @TayyabSalmanMRM1996,

We were looking at this issue, and for us in our retail app node_modules we don't have duplicate `adyen-web` dependecy. 
Can you please explain your use case and how got the duplicate adyen-web libraries in node modules?

Thanks
Aleksandar
Adyen

**Comment by TayyabSalmanMRM1996** [comment]
Thanks @amihajlovski, you can close the ticket. I'll get back if need anything else on this.
