### ISSUE TITLE
Use of body-parser in SSR.js

### ISSUE THREAD

**Issue by nx-olewolf** [Adyen/adyen-salesforce-headless-commerce-pwa#147]
Dear Team,
since version 2.0.0 of PWA Kit the body parser is not included anymore in the pwa kit. Can you add the parser to the middleware in each call which needs it?

From pwa kit they delete the parser because they have issues with the proxy.

**Comment by amihajlovski** [comment]
Hey @nx-olewolf 

We expected that the merchant will add the body-parser in their ssr.js file.
Here is how we use it in our demo retail app [LINK](https://github.com/Adyen/adyen-salesforce-headless-commerce-pwa/blob/main/packages/adyen-retail-react-app/overrides/app/ssr.js#L38)

If this doesn't help than we can consider some other solution.

Kind Regards
Aleksandar
Adyen

**Comment by nx-olewolf** [comment]
@amihajlovski  yes sure that is the way we fix it for now but i think there is reason why the sf team delete it. So maybe it would be a good solution to handle it in the middleware.

**Comment by amihajlovski** [comment]
Hey @nx-olewolf 

Sure, sounds good, we will do the investigation internally.

Thanks for raising this,
Aleksandar
Adyen
