### ISSUE TITLE
[CRITICAL] Sensitive Adyen information is exposed to client side

### ISSUE THREAD

**Issue by vinhtrinh** [Adyen/adyen-salesforce-headless-commerce-pwa#97]
**Describe The Bug**

Sensitive Adyen information is exposed to client side through application configurations.
Please note that all application configurations are exposed to the client side through SSR.

**To Reproduce**

1. Start the `adyen-retail-react-app`
2. Go to any page
3. Open **Console** tab in the **Developer Tools**
4. Print the Adyen configurations by `window.__CONFIG__.app.sites[0].adyen`

**Expected Behavior**

Sensitive information such as API keys, webhook accounts, webhook passwords, etc., must not be exposed to the client side.

**Screenshots**

![adyen-configs](https://github.com/Adyen/adyen-salesforce-headless-commerce-pwa/assets/3766193/ebe82216-2611-4b7b-916b-63d34b879697)

**Additional Context**

The issue has been occurring since version `1.0.0-beta.4`, [Adyen Installation](https://www.npmjs.com/package/@adyen/adyen-salesforce-pwa?activeTab=readme#installation) step no. 6.

**Comment by amihajlovski** [comment]
Hello @vinhtrinh

Thanks for opening this issue. We are aware of it and working on a way to provide a better solution which will be provided in a new patch (beta) release.
Please take into consideration the beta version of our integration, and some of the properties are left out for debug purposes which won't be a case in the General Availability version released further this quarter. 

Kind Regards
Aleksandar
Adyen
